server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: hvitops-gateway
#  web:
#    cors:
#      allowed-origins: "*"
#      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
#      allowed-headers: "*"
#      max-age: 3600
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://hvitops-auth:8085
          predicates:
            - Path=/auth/**
        - id: appointments
          uri: http://hvitops-appointments:8081
          predicates:
            - Path=/appointments/**
        - id: laboratory-tests
          uri: http://hvitops-laboratory-tests:8082
          predicates:
            - Path=/laboratory-tests/**
        - id: records
          uri: http://hvitops-records:8083
          predicates:
            - Path=/records/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: hvitops-secret-key-for-jwt-token-validation-2024

logging:
  level:
    root: INFO
    com.hvitops: DEBUG
